name: carrot-protocol-cpi

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      working-directory: carrot-protocol-cpi

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          override-file: rust-toolchain 

      - name: Run fmt
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Publish crates
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: github.ref != 'refs/heads/main' # dry run if not main branch